name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:      
          key: ${{ secrets.SSH_PRIVATE_KEY }}       
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts  
        
      - name: Deploy to sandbox via rsync
        run: rsync --delete -avz ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/projet

      - name: Composer
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} 'cd /var/www/projet/code && composer install'

      - name: Migrations
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} 'cd /var/www/projet/code && composer dump-env prod && (yes | php bin/console doctrine:cache:clear-metadata || true) && (yes | php bin/console doctrine:migrations:diff || true) && (yes | php bin/console doctrine:migrations:migrate || true)'

      - name: Groupe
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} 'cd /var/www/projet/code && chgrp -R www-data public && chmod g+w public'
