name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:      
          key: ${{ secrets.SSH_PRIVATE_KEY }}       
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOSTNAME }} >> ~/.ssh/known_hosts
          
      - name: Deploy to sandbox via rsync
        run: rsync -avz . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/projet
